server:
  port: 8384
spring:

  # ViewResolver
  mvc:
    view:
      #      static-path-pattern: /resources/
      prefix: /WEB-INF/views/
      suffix: .jsp

  servlet:
    jsp:
      init-parameters:
        development: true

  # h2
  h2:
    console:
      enabled: true
      path: /console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/./test
    username: oliver
    password: 3083

  # jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      generate-ddl: true
      show-sql: true


  # security, oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 336933391284-s30eosc9ntk57o0jsvhj9kv55gnopfsi.apps.googleusercontent.com
            client-secret: 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
            redirectUri: http://localhost:8384/login/oauth2/code/google
            scope:
              - email
              - profile
          kakao:
            authorization-grant-type: authorization_code
            client-id: 5c2d0f358423371eec07abdbc5143497
            client-secret: wYcGDUpe0nKj3TubMCKZmBX5Ed9SdcI1
            redirect-uri: http://localhost:8384/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-authentication-method: POST
            client-name: Kakao

        provider:

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  profiles:
    include: oauth


